'use strict';
const $=s=>document.querySelector(s), el=(tag,text,cls)=>{let n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
let token=location.hash.slice(1)||sessionStorage.getItem('abh-token')||'';if(location.hash){sessionStorage.setItem('abh-token',token);history.replaceState(null,'',location.pathname);}
let data,page='Overview';const pages=['Overview','Programs','Scope','Assets','Endpoints','Analyze traffic','Agents','Jobs','Findings','Evidence','Reports','Activity','Settings'];
const labels=s=>String(s||'—').replaceAll('_',' '), short=s=>String(s||'').slice(0,12);
function button(label,fn,cls){let b=el('button',label,cls);b.onclick=async()=>{try{await fn();}catch(e){$('#message').textContent=e.message;}};return b;}
async function api(path,body){let r=await fetch(path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+token,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});let v=await r.json();if(!r.ok)throw Error(v.error||'Request failed');return v;}
async function act(body){await api('/api/action',body);$('#message').textContent='Saved. The workspace has been refreshed.';await refresh();}
function panel(title){let p=el('div',undefined,'panel');p.append(el('h2',title));return p;}
function empty(parent,title,detail){let e=el('div',undefined,'empty');e.append(el('strong',title),el('span',detail));parent.append(e);}
function table(parent,headers,rows){if(!rows.length){empty(parent,'Nothing here yet','Records will appear as you add authorized research data.');return;}let wrap=el('div',undefined,'table-wrap'),t=el('table'),head=el('tr');headers.forEach(h=>head.append(el('th',h)));let thead=el('thead');thead.append(head);t.append(thead);let body=el('tbody');rows.forEach(row=>{let tr=el('tr');row.forEach(cell=>{let td=el('td');if(cell instanceof Node)td.append(cell);else td.textContent=cell??'—';tr.append(td);});body.append(tr);});t.append(body);wrap.append(t);parent.append(wrap);}
function badge(text){return el('span',labels(text),'badge');}
function objectRows(kind){return data.objects.filter(o=>o.kind===kind);}
function show(title,node){$('#detail-title').textContent=title;$('#detail-body').replaceChildren(node);$('#detail').showModal();}
function rawDetails(title,item){let p=el('pre',JSON.stringify(item,null,2));show(title,p);}
function render(){ $('#title').textContent=page;let root=$('#content');root.replaceChildren();document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.textContent===page));$('#stop').textContent=data.engine.stopped?'Resume engine':'Emergency stop';
 if(page==='Overview'){
 let hero=el('div',undefined,'hero'),copy=el('div');copy.append(el('h2','Your research, with the evidence in view.'),el('p','Review authorized work, follow every observation, and keep the final decision in your hands.'));hero.append(copy,el('div','◈','mark'));root.append(hero);
 let stats=el('div',undefined,'stats');[['Programs',data.programs.length,'Authorization policies'],['Assets',objectRows('asset').length,'Recorded in this workspace'],['Candidate findings',objectRows('finding').length,'Review before making a claim'],['Awaiting approval',data.jobs.filter(j=>j.status==='waiting_human').length,'Jobs needing your decision']].forEach(([name,count,hint])=>{let c=el('div',undefined,'stat');c.append(el('label',name),el('strong',count),el('small',hint));stats.append(c);});root.append(stats);
 let grid=el('div',undefined,'grid'),recent=panel('Recent investigations'),activity=panel('Workspace status');objectRows('finding').slice(0,5).forEach(f=>{let row=el('div',undefined,'row'),text=el('div');text.append(el('strong',f.payload.title),el('small',f.target));row.append(text,button('Review →',()=>finding(f.id)));recent.append(row);});if(!objectRows('finding').length)empty(recent,'Ready for your first investigation','Import observations and evidence from an authorized lab.');[['Execution',data.engine.stopped?'Stopped':'Dry run only'],['Burp Community','XML import ready · live connection unverified'],['Model providers','Offline contracts · no live calls'],['Reports','Human approval required · submission disabled']].forEach(([a,b])=>{let row=el('div',undefined,'activity-line');row.append(el('strong',a),el('div',b,'muted'));activity.append(row);});grid.append(recent,activity);root.append(grid);
 }else if(page==='Programs'||page==='Scope'){let p=panel(page==='Programs'?'Program policies':'Authorized scope and exclusions');table(p,['PROGRAM','AUTHORIZATION',page==='Programs'?'VALID UNTIL':'SCOPE RULES',''],data.programs.map(x=>[x.name,badge(x.authorization_status),page==='Programs'?x.valid_until:x.scope.length,button('Inspect',()=>rawDetails(x.name,x))]));root.append(p);
 }else if(['Assets','Endpoints','Findings','Evidence','Reports'].includes(page)){let kind={Assets:'asset',Endpoints:'endpoint',Findings:'finding',Evidence:'evidence',Reports:'report'}[page],p=panel(page);table(p,['RECORD','TARGET','STATE',''],objectRows(kind).map(o=>[o.payload.title||o.payload.label||o.payload.target||short(o.id),o.target,badge(o.status),button('Open →',()=>kind==='finding'?finding(o.id):kind==='evidence'?evidence(o.id):kind==='report'?report(o):rawDetails(page,o))]));root.append(p);
 }else if(page==='Jobs'){let p=panel('Job queue');table(p,['ACTION','TARGET','STATUS','OWNER','REVIEW'],data.jobs.map(j=>{let actions=el('div');if(j.status==='waiting_human'){actions.append(button('Approve',()=>act({action:'approve_job',id:j.id})),button('Reject',()=>act({action:'reject_job',id:j.id})));}actions.append(button('Details',()=>rawDetails('Job '+short(j.id),j)));return [labels(j.type),j.target,badge(j.status),j.owner,actions];}));root.append(p);
 }else if(page==='Agents'){let p=panel('Specialized agents');data.agents.forEach(a=>{let row=el('div',undefined,'row'),text=el('div');text.append(el('strong',a.name),el('small',a.responsibility));row.append(text,badge('offline'));p.append(row);});root.append(p);
 }else if(page==='Analyze traffic'){
 let upload=panel('Import a Burp capture');upload.append(el('p','Choose exported XML with Base64 encoding enabled. Your file is stored only in this local workspace.','muted'));
 let program=el('select');program.setAttribute('aria-label','Capture program');data.programs.forEach(x=>{let option=el('option',x.name);option.value=x.id;program.append(option);});
 let file=el('input');file.type='file';file.accept='.xml';file.setAttribute('aria-label','Burp XML capture');
 upload.append(program,file,button('Import capture',async()=>{if(!program.value||!file.files.length)throw Error('Choose a program and an XML file.');let selected=file.files[0];if(selected.size>10*1024*1024)throw Error('Capture must be at most 10 MiB.');let bytes=new Uint8Array(await selected.arrayBuffer()),binary='';for(let i=0;i<bytes.length;i+=32768)binary+=String.fromCharCode(...bytes.subarray(i,i+32768));await api('/api/import-burp',{program:program.value,base64:btoa(binary)});$('#message').textContent='Capture imported. Choose Analyze below to detect candidates.';await refresh();}));root.append(upload);
 let captures=panel('Detect candidates from recorded traffic');captures.append(el('p','These checks inspect existing evidence. Each candidate explains the observed behavior and what still needs validation.','muted'));
 let inputs=data.integrations.filter(r=>['burp_import','manual_http_baseline'].includes(r.kind));table(captures,['CAPTURE','PROGRAM',''],inputs.map(r=>[labels(r.kind)+' · '+short(r.id),r.program_id,button('Analyze',async()=>{let result=await api('/api/action',{action:'analyze_traffic',id:r.id});let count=result.result.payload.candidate_count;$('#message').textContent=count+' candidate(s) found. Review their evidence in Findings.';await refresh();await assessment(result.result.id);})]));root.append(captures);
 let assessments=panel('Saved assessments');table(assessments,['WHEN','CANDIDATES',''],data.integrations.filter(r=>r.kind==='traffic_analysis').slice().reverse().map(r=>[r.created_at.slice(0,19),r.payload.candidate_count,button('Read assessment',()=>assessment(r.id))]));root.append(assessments);
 }else if(page==='Activity'){let p=panel('Traceable decisions and imports');table(p,['WHEN','TYPE','PROGRAM',''],data.integrations.slice().reverse().map(r=>[r.created_at.slice(0,19),labels(r.kind),r.program_id,button('Inspect',()=>rawDetails(labels(r.kind),r))]));root.append(p);
 }else{let p=panel('Development connections');p.append(el('p','This dashboard runs only on your computer. Live Kali, model-provider and Telegram connections are not configured.','muted'));data.models.forEach(m=>{let row=el('div',undefined,'row');row.append(el('strong',m.provider),badge(m.enabled?'configured':'disabled'));p.append(row);});p.append(el('p','Evidence and credentials stay out of the GitHub repository. Local access links are private to this dashboard session.','muted'));root.append(p);}
}
async function evidence(id,container){let result=await api('/api/evidence?id='+encodeURIComponent(id)),p=container||el('div');p.append(el('h3',result.metadata.payload.label),el('p',labels(result.metadata.payload.origin)+' · SHA-256 '+result.metadata.payload.sha256,'mono'));let bytes=Uint8Array.from(atob(result.base64),c=>c.charCodeAt(0));let mime=bytes[0]===137&&bytes[1]===80?'image/png':bytes[0]===255&&bytes[1]===216?'image/jpeg':null;if(mime){let img=el('img');img.className='preview';img.alt=result.metadata.payload.label;let url=URL.createObjectURL(new Blob([bytes],{type:mime}));img.src=url;img.onload=()=>URL.revokeObjectURL(url);p.append(img);}else p.append(el('pre',new TextDecoder().decode(bytes.slice(0,65536))));p.append(button('Download original',()=>{let url=URL.createObjectURL(new Blob([bytes],{type:'application/octet-stream'})),a=el('a');a.href=url;a.download=id+'.bin';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}));if(!container)show('Evidence',p);}
async function finding(id){let state=await api('/api/finding?id='+encodeURIComponent(id)),f=state.finding,wrap=el('div');wrap.append(badge(state.status));let steps=el('div',undefined,'steps');['Program','Asset','Endpoint','Observation','Candidate','Evidence','Human review'].forEach(s=>steps.append(el('span',s)));wrap.append(steps);let grid=el('div',undefined,'detail-grid'),left=panel('Reasoning & provenance'),right=panel('Original evidence');left.append(el('h3','Hypothesis'),el('p',f.payload.hypothesis),el('h3','Target'),el('p',f.target,'mono'),el('h3','How this was recorded'));(state.provenance||[]).forEach(item=>{let line=el('div',undefined,'row'),body=el('div');body.append(el('strong',item.kind),el('small',(item.payload.title||item.payload.fact||item.payload.target||item.id).slice(0,220)));line.append(body,badge(item.status));left.append(line);});left.append(el('h3','What remains uncertain'),el('p','Imported observations and evidence require human verification. No live validation or model analysis is implied.','muted'));state.reviews.forEach(r=>left.append(el('pre',JSON.stringify(r.payload,null,2))));if(!state.evidence.length)empty(right,'Evidence needed','Attach original captures before validation.');for(let e of state.evidence){let section=el('div');await evidence(e.id,section);right.append(section);}grid.append(left,right);wrap.append(grid);
 let review=panel('Your review'),checks={};[['real','The behavior is real'],['reproducible','I reproduced it'],['in_scope','The target is in scope'],['security_relevant','There is a security impact'],['not_duplicate','This is not a duplicate'],['evidence_sufficient','The evidence supports the claim']].forEach(([key,label])=>{let l=el('label',undefined,'check'),input=el('input');input.type='checkbox';checks[key]=input;l.append(input,document.createTextNode(label));review.append(l);});let reason=el('textarea');reason.placeholder='Explain your decision and any remaining uncertainty';reason.setAttribute('aria-label','Review rationale');review.append(reason);let actions=el('div',undefined,'actions');[['Validate','validated'],['Needs evidence','needs_evidence'],['False positive','false_positive']].forEach(([label,decision])=>actions.append(button(label,async()=>{await act({action:'review_finding',id,decision,checks:Object.fromEntries(Object.entries(checks).map(([k,v])=>[k,v.checked])),rationale:reason.value});$('#detail').close();await finding(id);})));review.append(actions);wrap.append(review);
 if(state.status==='validated'){let draft=panel('Prepare a report'),title=el('input');title.value=f.payload.title;title.setAttribute('aria-label','Report title');let question=el('input');question.value='Steps to reproduce';question.setAttribute('aria-label','Exact program question');let answer=el('textarea');answer.placeholder='Your evidence-backed answer';answer.setAttribute('aria-label','Report answer');draft.append(title,question,answer,button('Create draft for review',async()=>{await act({action:'draft_report',id,title:title.value,questions:[{id:'q1',label:question.value,answer:answer.value,evidence_ids:state.evidence.filter(e=>e.payload.origin==='raw_import').map(e=>e.id)}]});$('#detail').close();page='Reports';render();}));wrap.append(draft);}show(f.payload.title,wrap);}
function report(o){let p=el('div');p.append(el('p','Review every answer beside its source evidence. Approval does not submit this report.','notice'));o.payload.questions.forEach(q=>{let c=panel(q.label);c.append(el('p',q.answer||'Unanswered'));q.evidence_ids.forEach(id=>c.append(button('Inspect evidence '+short(id),()=>evidence(id))));p.append(c);});let workflow=data.integrations.filter(r=>r.kind==='report_workflow'&&r.payload.report_id===o.id);p.append(el('pre',JSON.stringify(workflow.map(r=>r.payload),null,2)),button('Approve report locally',async()=>{await act({action:'approve_report',id:o.id});$('#detail').close();}));show(o.payload.title,p);}
async function refresh(){data=await api('/api/overview');render();}
async function assessment(id){let result=await api('/api/analysis-report?id='+encodeURIComponent(id)),wrap=el('div');wrap.append(el('p','These are candidates from captured traffic. Human validation is required before a vulnerability report.','notice'),el('pre',result.markdown),button('Download assessment',()=>{let url=URL.createObjectURL(new Blob([result.markdown],{type:'text/markdown;charset=utf-8'})),a=el('a');a.href=url;a.download='assessment-'+short(id)+'.md';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}));show('Traffic assessment',wrap);}
pages.forEach(name=>$('#nav').append(button(name,()=>{page=name;render();})));$('#close').onclick=()=>$('#detail').close();$('#refresh').onclick=()=>refresh().catch(e=>$('#message').textContent=e.message);$('#stop').onclick=()=>act({action:data.engine.stopped?'resume':'stop'}).catch(e=>$('#message').textContent=e.message);refresh().catch(e=>$('#message').textContent=e.message);
